apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fvmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fvmt
    app.kubernetes.io/part-of: byoc-app-xzfo
  name: fvmt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: fvmt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: fvmt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-zarg-tenant/byoc-app-xzfo/fvmt@sha256:09d4a9feb99a8373b3d337f823af74f465124b74729462c8985a0c1eb448f56f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
