apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fvmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fvmt
    app.kubernetes.io/part-of: byoc-app-xzfo
  name: fvmtfa5w
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: fvmt
    weight: null
status: {}
